# Generated by Django 3.2.4 on 2021-07-01 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='users/pictures/default.png', null=True, upload_to='users/pictures/', verbose_name='Profile picture'),
        ),
    ]
