# Generated by Django 3.2.4 on 2021-07-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='retweet',
            field=models.BooleanField(default=False),
        ),
    ]
